In [3]:
# 7.2 Creating arrays from Existing Data

import numpy as np

numbers = np.array([2, 3, 5, 7, 11])

print(type(numbers))
print(numbers)

print(np.array([[1, 2, 3], [4, 5, 6]]))

<class 'numpy.ndarray'>
[ 2  3  5  7 11]
[[1 2 3]
 [4 5 6]]


In [4]:
# 7.2 Self-Check 2: Create a one-dimensional array from a list comprehension that produces the even integers from 2 through 20.

import numpy as np

np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
# 7.2 Self-Check 3: Create a 2-by-5 array containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row.

np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [12]:
# 7.3 examples

# array Attributes

import numpy as np

integers = np.array([[1, 2, 3], [4, 5, 6]])

floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

print(integers)
print(floats)

# Determining an array's Element type

print(integers.dtype)
print(floats.dtype)

# Determining an array's Dimensions

print(integers.ndim)
print(floats.ndim)
print(integers.shape)
print(floats.shape)

# Determining an array's Number of Elements and Element Size

print(integers.size)
print(integers.itemsize)
print(floats.size)
print(floats.itemsize)

# Iterating Through a Multidimensional array's Elements

for row in integers:
    for column in row:
        print(column, end=" ")
    print()
    
for i in integers.flat:
    print(i, end=' ')


[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4]
int32
float64
2
1
(2, 3)
(5,)
6
4
5
8
1 2 3 
4 5 6 
1 2 3 4 5 6 

In [13]:
# 7.3 Self-Check 2: For the two-dimensional array in the previous section’s Self Check, display the number of dimensions and shape of the array.

import numpy as np

a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

print(a.ndim)
print(a.shape)

2
(2, 5)


In [18]:
# 7.4 examples

# Filling arrays with Specific Values

import numpy as np

print(np.zeros(5))

print(np.ones((2, 4), dtype=int))

print(np.full((3, 5), 13))

[0. 0. 0. 0. 0.]
[[1 1 1 1]
 [1 1 1 1]]
[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]


In [24]:
# 7.5 examples

# Creating arrays from Ranges

# Creating Integer ranges with arange

import numpy as np

print(np.arange(5))

print(np.arange(5, 10))

print(np.arange(10, 1, -2))

# Creating Floating-Point Ranges with linspace

print(np.linspace(0.0, 1.0, num=5))

# Reshaping an array

print(np.arange(1, 21).reshape(4, 5))

# Displaying Large arrays

print(np.arange(1, 100001).reshape(4, 25000))

print(np.arange(1, 100001).reshape(100, 1000))

[0 1 2 3 4]
[5 6 7 8 9]
[10  8  6  4  2]
[0.   0.25 0.5  0.75 1.  ]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[     1      2      3 ...  24998  24999  25000]
 [ 25001  25002  25003 ...  49998  49999  50000]
 [ 50001  50002  50003 ...  74998  74999  75000]
 [ 75001  75002  75003 ...  99998  99999 100000]]
[[     1      2      3 ...    998    999   1000]
 [  1001   1002   1003 ...   1998   1999   2000]
 [  2001   2002   2003 ...   2998   2999   3000]
 ...
 [ 97001  97002  97003 ...  97998  97999  98000]
 [ 98001  98002  98003 ...  98998  98999  99000]
 [ 99001  99002  99003 ...  99998  99999 100000]]


In [26]:
# 7.5 Self-check 2: Use NumPy function arange to create an array of 20 even integers from 2 through 40, then reshape the result into a 4-by-5 array.

import numpy as np

print(np.arange(2, 41, 2).reshape(4, 5))

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [31]:
# 7.6 examples

# List vs. array Performance: Introducing %timeit

# Timing the Creation of a List Containing Results of 6,000,000 Die Rolls

import random

%timeit rolls_list = [random.randrange(1, 7) for i in range(0, 6_000_000)]

# Timing the Creation of an array Containing Results of 6,000,000 Die Rolls

import numpy as np

%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

# 60,000,000 and 600,000,000 Die Rolls

%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

7.35 s ± 43.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
52.6 ms ± 236 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
506 ms ± 3.84 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5.09 s ± 14.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
52 ms ± 151 µs per loop (mean ± std. dev. of 2 runs, 3 loops each)


In [32]:
# 7.6 Self-check 1: Use %timeit to compare the execution time of the following two statements. 
# sum([x for x in range(10_000_000)])
# np.arange(10_000_000).sum()
# The first uses a list comprehension to create a list of the integers from 0 to 9,999,999, then totals them with the built-in sum function. 
# The second statement does the same thing using an array and its sum method.

import numpy as np

%timeit sum([x for x in range(10_000_000)])

%timeit np.arange(10_000_000).sum()
 

993 ms ± 22.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
19.5 ms ± 1.88 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [36]:
# 7.7 examples

# array Operators

# Arithmetic Operations with arrays and Individual Numeric Values

import numpy as np

numbers = np.arange(1, 6)

print(numbers)
print(numbers * 2)
print(numbers ** 3)
print(numbers) # numbers is unchanged by the arithmetic operators

numbers += 10
print(numbers)

# Arithmetic Operations Between arrays

numbers2 = np.linspace(1.1, 5.5, 5)

print(numbers2)
print(numbers * numbers2)

# Comparing arrays

print(numbers)
print(numbers >= 13)
print(numbers2)
print(numbers2 < numbers)
print(numbers == numbers2)
print(numbers == numbers)

[1 2 3 4 5]
[ 2  4  6  8 10]
[  1   8  27  64 125]
[1 2 3 4 5]
[11 12 13 14 15]
[1.1 2.2 3.3 4.4 5.5]
[12.1 26.4 42.9 61.6 82.5]
[11 12 13 14 15]
[False False  True  True  True]
[1.1 2.2 3.3 4.4 5.5]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]


In [37]:
# 7.7 Self-Check 2: Create an array of the values from 1 through 5, then use broadcasting to square each value.

import numpy as np

print(np.arange(1, 6) ** 2)

[ 1  4  9 16 25]


In [43]:
# 7.8 examples

# NumPy Calculation Methods

import numpy as np

grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

print(grades)

print(grades.sum())
print(grades.min())
print(grades.max())
print(grades.mean())
print(grades.std())
print(grades.var())

# Calculations by Row or column

print(grades.mean(axis=0))
print(grades.mean(axis=1))

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]
1054
70
100
87.83333333333333
8.792357792739987
77.30555555555556
[95.25 85.25 83.  ]
[84.33333333 92.33333333 87.         87.66666667]


In [44]:
# 7.8 Self-Check 2: Use NumPy random-number generation to create an array of twelve random grades in the range 60 through 100, 
# then reshape the result into a 3-by-4 array. Calculate the average of all the grades, the averages of the grades in each column 
# and the averages of the grades in each row.

import numpy as np

grades = np.random.randint(60, 101, 12).reshape(3, 4)

print(grades)
print(grades.mean())  # mean of all grades
print(grades.mean(axis=0))  # mean of grades in each column
print(grades.mean(axis=1))  # mean of grades in each row

[[68 86 83 78]
 [68 76 62 89]
 [70 75 98 88]]
78.41666666666667
[68.66666667 79.         81.         85.        ]
[78.75 73.75 82.75]


In [50]:
# 7.9 examples

# Universal Functions

import numpy as np

numbers = np.array([1, 4, 9, 16, 25, 36])

print(np.sqrt(numbers))

numbers2 = np.arange(1, 7) * 10

print(numbers)
print(numbers2)
print(np.add(numbers, numbers2))

# Broadcasting with Universal Functions

print(np.multiply(numbers2, 5))

numbers3 = numbers2.reshape(2, 3)

print(numbers3)

numbers4 = np.array([2, 4, 6])

print(np.multiply(numbers3, numbers4))

[1. 2. 3. 4. 5. 6.]
[ 1  4  9 16 25 36]
[10 20 30 40 50 60]
[11 24 39 56 75 96]
[ 50 100 150 200 250 300]
[[10 20 30]
 [40 50 60]]
[[ 20  80 180]
 [ 80 200 360]]


In [52]:
# 7.9 Self-Check 2: Create an array of the values from 1 through 5, then use the power universal function and broadcasting to cube each value.

import numpy as np

numbers = np.arange(1, 6)

print(np.power(numbers, 3))

[  1   8  27  64 125]


In [56]:
# 7.10 examples

# Indexing and Slicing

# Indexing with Two-Dimensional arrays

import numpy as np

grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

print(grades)

print(grades[0, 1])  # row 0, column 1

# Selecting a sub-set of a Two-Dimensional array's Rows

print(grades[1])
print(grades[0:2])
print(grades[[1, 3]])

# Selecting a sub-set of a Two-Dimensional array's Columns

print(grades[:, 0])
print(grades[:, 1:3])
print(grades[:, [0, 2]])

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]
96
[100  87  90]
[[ 87  96  70]
 [100  87  90]]
[[100  87  90]
 [100  81  82]]
[ 87 100  94 100]
[[96 70]
 [87 90]
 [77 90]
 [81 82]]
[[ 87  70]
 [100  90]
 [ 94  90]
 [100  82]]


In [58]:
# 7.10 Self-Check 1: given the following array:
# array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
# write statements to perform the following tasks:
# a. Select the second row
# b. Select the first and third rows
# c. Select the middle three columns

import numpy as np

bearcat = np.arange(1, 16).reshape(3, 5)

print(bearcat[1])
print(bearcat[[0, 2]])
print(bearcat[:, 1:4])

[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [66]:
# 7.11 examples

# Views: Shallow Copies

import numpy as np

numbers = np.arange(1, 6)

print(numbers)

numbers2 = numbers.view()

print(numbers2)

print(id(numbers))
print(id(numbers2))

numbers[1] *= 10

print(numbers2)
print(numbers)

numbers2[1] /= 10

print(numbers)
print(numbers2)

# Slice Views

numbers2 = numbers[0:3]

print(numbers2)

print(id(numbers))
print(id(numbers2))

numbers[1] *= 20

print(numbers)
print(numbers2)

[1 2 3 4 5]
[1 2 3 4 5]
2508073117424
2508050828432
[ 1 20  3  4  5]
[ 1 20  3  4  5]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3]
2508073117424
2508072246704
[ 1 40  3  4  5]
[ 1 40  3]


In [68]:
# 7.12 examples 

# Deep Copies

import numpy as np

numbers = np.arange(1, 6)

print(numbers)

numbers2 = numbers.copy()

print(numbers2)

numbers[1] *= 10

print(numbers)
print(numbers2)

[1 2 3 4 5]
[1 2 3 4 5]
[ 1 20  3  4  5]
[1 2 3 4 5]


In [81]:
# 7.13 examples

# Reshaping and Transposing

# reshape vs. resize

import numpy as np

grades = np.array([[87, 96, 70], [100, 87, 90]])

print(grades)

print(grades.reshape(1, 6))

print(grades)

grades.resize(1, 6)

print(grades)

# flatten vs. ravel

grades = np.array([[87, 96, 70], [100, 87, 90]])

print(grades)

flattened = grades.flatten()

print(flattened)

print(grades)

flattened[0] = 100

print(flattened)
print(grades)

raveled = grades.ravel()

print(raveled)
print(grades)

raveled[0] = 100

print(raveled)
print(grades)

# Transposing Rows and Columns

print(grades.T)
print(grades)

# Horizontal and Vertical Stacking

grades2 = np.array([[94, 77, 90], [100, 81, 82]])

print(np.hstack((grades, grades2)))
print(np.vstack((grades, grades2)))

[[ 87  96  70]
 [100  87  90]]
[[ 87  96  70 100  87  90]]
[[ 87  96  70]
 [100  87  90]]
[[ 87  96  70 100  87  90]]
[[ 87  96  70]
 [100  87  90]]
[ 87  96  70 100  87  90]
[[ 87  96  70]
 [100  87  90]]
[100  96  70 100  87  90]
[[ 87  96  70]
 [100  87  90]]
[ 87  96  70 100  87  90]
[[ 87  96  70]
 [100  87  90]]
[100  96  70 100  87  90]
[[100  96  70]
 [100  87  90]]
[[100 100]
 [ 96  87]
 [ 70  90]]
[[100  96  70]
 [100  87  90]]
[[100  96  70  94  77  90]
 [100  87  90 100  81  82]]
[[100  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]


In [83]:
# 7.13 Self-Check 1: Given a 2x3 array:
# array([[1, 2, 3],
#       [4, 5, 6]])
# use hstack and vstack to produce the following array:
# array([[1, 2, 3, 1, 2, 3],
#        [4, 5, 6, 4, 5, 6],
#        [1, 2, 3, 1, 2, 3],
#        [4, 5, 6, 4, 5, 6]])

import numpy as np

bearcat = np.arange(1, 7).reshape(2, 3)

bearcat = np.hstack((bearcat, bearcat))

bearcat = np.vstack((bearcat, bearcat))

print(bearcat)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [99]:
# 7.14.1 practice

# pandas series

import pandas as pd

# Creating a Series with Default Indices

grades = pd.Series([87, 100, 94])

# Displaying a series

print(grades)

# Creating a Series with all elements haveing the same value

print(pd.Series(98.6, range(3)))

# Acessing a Series' Elements

print(grades[0])

# Producing Descriptive Statistics for a Series

print(grades.count())
print(grades.mean())
print(grades.min())
print(grades.max())
print(grades.std())

print(grades.describe())

# Creating a Series with custom indices

grades = pd.Series([87, 100, 94], index=['Wally', 'Eva', 'Sam'])

print(grades)

# Dictionary Initializers

grades = pd.Series({'Wally': 87, 'Eva': 100, 'Sam': 94})

print(grades)

# Accessing elements of a Series via Custom Indices

print(grades['Eva'])
print(grades.Wally)
print(grades.dtype)
print(grades.values)

# Creating a Series of Strings

hardware = pd.Series(['Hammer', 'Saw', 'Wrench'])

print(hardware)
print(hardware.str.contains('a'))

print(hardware.str.upper())

0     87
1    100
2     94
dtype: int64
0    98.6
1    98.6
2    98.6
dtype: float64
87
3
93.66666666666667
87
100
6.506407098647712
count      3.000000
mean      93.666667
std        6.506407
min       87.000000
25%       90.500000
50%       94.000000
75%       97.000000
max      100.000000
dtype: float64
Wally     87
Eva      100
Sam       94
dtype: int64
Wally     87
Eva      100
Sam       94
dtype: int64
100
87
int64
[ 87 100  94]
0    Hammer
1       Saw
2    Wrench
dtype: object
0     True
1     True
2    False
dtype: bool
0    HAMMER
1       SAW
2    WRENCH
dtype: object


In [104]:
# 7.14.1 Self-Check 1: Use the NumPy’s random-number generation to create an array of five random integers that represent 
# summertime temperatures in the range 60–100, then perform the following tasks:


# Produce descriptive statistics for the Series.

import numpy as np
import pandas as pd

temps = np.random.randint(60, 101, 5)

temperatures = pd.Series(temps)

# Convert the array into the Series named temperatures and display it.
print(temperatures)

# Determine the lowest, highest and average temperatures.
print(temperatures.min())
print(temperatures.max())
print(temperatures.mean())

# Produce descriptive statistics for the Series.
print(temperatures.describe())

0    100
1     80
2     83
3     78
4     60
dtype: int32
60
100
80.2
count      5.000000
mean      80.200000
std       14.254824
min       60.000000
25%       78.000000
50%       80.000000
75%       83.000000
max      100.000000
dtype: float64


In [31]:
# 7.14.2 examples

# DataFrames

# Creating a DataFrame from a Dictionary

import pandas as pd

grades_dict = {'Wally': [87, 96, 70], 'Eva': [100, 87, 90], 'Sam': [94, 77, 90], 'Katie': [100, 81, 82], 'Bob': [83, 65, 85]}

grades = pd.DataFrame(grades_dict)

print(grades)

# Customizing a DataFrame's Indicies with the index Attribute

grades.index = ['Test1', 'Test2', 'Test3']

print(grades)

# Accessing a DataFrame's Columns

print(grades['Eva'])
print(grades.Sam)

# Selecting rows via the loc and iloc attributes

print(grades.loc['Test1'])
print(grades.iloc[1])

# Selecting Rows via Slices and Lists with loc and iloc Attributes

print(grades.loc['Test1':'Test3']) # includes high index
print(grades.iloc[0:2])  # excludes high index
print(grades.loc[['Test1', 'Test3']])
print(grades.iloc[[0, 2]])

# Selecting subsets of the rows and columns

print(grades.loc['Test1':'Test2', ['Eva', 'Katie']])
print(grades.iloc[[0, 2], 0:3])

# Boolean Indexing

print(grades[grades >= 90])
print(grades[(grades >= 80) & (grades < 90)])

# Accessing a specific DataFrame cell by row and column

print(grades.at['Test2', 'Eva'])
print(grades.iat[2, 0])

grades.at['Test2', 'Eva'] = 100

print(grades.at['Test2', 'Eva'])

grades.iat[1, 2] = 87

print(grades.iat[1, 2])

# Descriptive Statistics

print(grades.describe())

pd.set_option('precision', 2)

print(grades.describe())

print(grades.mean())

# Transposing the DataFrame with the T attribute

print(grades.T)  # transposed
print(grades.T.describe())  # descrition based on transposed DataFrame
print(grades.T.mean())  # mean of transposed DataFrame

# Sorting by rows by their indices

print(grades.sort_index(ascending=False))

# Sorting by Column indices

print(grades.sort_index(axis=1))

# Sorting by Column values

print(grades.sort_values(by='Test1', axis=1, ascending=False))
print(grades.T.sort_values(by='Test1', ascending=False))
print(grades.loc['Test1'].sort_values(ascending=False))



   Wally  Eva  Sam  Katie  Bob
0     87  100   94    100   83
1     96   87   77     81   65
2     70   90   90     82   85
       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85
Test1    100
Test2     87
Test3     90
Name: Eva, dtype: int64
Test1    94
Test2    77
Test3    90
Name: Sam, dtype: int64
Wally     87
Eva      100
Sam       94
Katie    100
Bob       83
Name: Test1, dtype: int64
Wally    96
Eva      87
Sam      77
Katie    81
Bob      65
Name: Test2, dtype: int64
       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
Test3     70   90   90     82   85
       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test2     96   87   77     81   65
       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   90   90     82   85
       Wally  Eva  Sam  Katie  Bob
Test1     87  100   94    100   83
Test3     70   9

In [38]:
# 7.14 Self-Check 1: Given the following dictionary;
# temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82], 'Thu': [75, 97], 'Fri': [62, 79]}
# perform the following tasks:
# Convert the dictionary into the DataFrame named temperatures with 'Low' and 'High' as the indices, then display the DataFrame.
# Use the column names to select only the columns for 'Mon' through 'Wed'.
# Use the row index 'Low' to select only the low temperatures for each day.
# Set the floating-point precision to 2, then calculate the average temperature for each day.
# Calculate the average low and high temperatures.

import pandas as pd

temps = {'Mon': [68, 89], 'Tue': [71, 93], 'Wed': [66, 82], 'Thu': [75, 97], 'Fri': [62, 79]}

temperatures = pd.DataFrame(temps, index=['Low', 'High'])

print(temperatures)

print(temperatures.loc[:, 'Mon':'Wed'])

print(temperatures.loc['Low'])

pd.set_option('precision', 2)

print(temperatures.mean())

print(temperatures.mean(axis=1))

      Mon  Tue  Wed  Thu  Fri
Low    68   71   66   75   62
High   89   93   82   97   79
      Mon  Tue  Wed
Low    68   71   66
High   89   93   82
Mon    68
Tue    71
Wed    66
Thu    75
Fri    62
Name: Low, dtype: int64
Mon    78.5
Tue    82.0
Wed    74.0
Thu    86.0
Fri    70.5
dtype: float64
Low     68.4
High    88.0
dtype: float64
